### PR TITLE
Fixing the about link button (CSS)

### PR DESCRIPTION
**Pull request by Darkcodelab**
Made the about-link button's position relative to the viewport

### CODE REVIEW

**Comment by bushblade** [comment]
Hi @Darkcodelab 
Do you have a reproduce-able example of this please?
A few students have mentioned there is an issue here but so far I have not been able to reproduce it myself.

**Comment by Darkcodelab** [comment]
Hi @bushblade 
Yeah here's what I did, I've added a bunch of feedback and when I scroll down, the `about-link` button is not sticking to the bottom of the page.
img_1
img_2

**Comment by bushblade** [comment]
Thanks for that, yes I see the issue.
I'm not sure the fix you suggest is the best one though as then the link would appear over the top of the feedback cards and with them having the same background color as the icon color you wouldn't be able to see it.
So I think the best solution would be not to use `position: fixed` as that takes it out of the document flow and instead change...
```css
.about-link {
  position: absolute;
  bottom: 20px;
  right: 20px;
  color: #fff;
  cursor: pointer;
}

.about-link a {
  color: #fff;
}
```
to
```css
.about-link {
  display: flex;
  justify-content: flex-end;
}

.about-link a {
  color: #fff;
  cursor: pointer;
}
```
That way the div stays at the bottom all the time and so over the purple background and stays visible.

**Comment by bushblade** [comment]
[I added a fix to the bugfix branch.](https://github.com/bradtraversy/feedback-app/commit/c4c5a217d18584e75a9b68dd34db8be15a99da17)
We will update that branch for now with all bug fixes and then merge and keep an originalcoursecode branch so as students will still have reference to the code they see in the course.

**Comment by Darkcodelab** [comment]
Good point bushblade. Thanks for the update

**Pull request closed without merging**
